### ISSUE TITLE
Checklist before deprecation of sims_* packages

### ISSUE THREAD

**Issue by rhiannonlynne** [lsst-sims/migration_plan#3]
- [x] Run a 10 year simulation, compare against previous simulation
- [x] Run all metrics (glance, metadata, science, moving objects)
- [x] Run syseng throughputs style evaluation
- [x] License
- [x] conda installation available
- [x] installation documentation 
- [x] basic usage / transfer documentation
- [x] CI & testing
- [x] Notebook examples translated
